const fs = require('fs');

const languages = ['en', 'pl'];

const translations = {
  en: {
    drawer_page: {
      "title": "Digital Drawer",
      "subtitle": "Manage your contracts, equipment, and important documents",
      "tab_contracts": "Contracts & Subscriptions",
      "tab_warranties": "Equipment & Warranties",
      "tab_certificates": "Certificates & Other",
      "add_contract": "Add new contract",
      "add_warranty": "Add new equipment",
      "add_certificate": "Add new document",
      "delete_confirm": "Are you sure you want to remove this document from the drawer?",
      "progress_no_limit": "No time limit",
      "progress_expired": "Expired",
      "progress_left": "{days} days left",
      "empty_contracts": "You have no contracts added yet. Click the button above to add your first.",
      "empty_warranties": "No saved equipment and warranties.",
      "empty_certificates": "No saved certificates and documents.",
      "from_date": "From: ",
      "view_document": "View document",
      "cost_recurring": "/ cycle",
      "cost_one_time": "one-time",
      "status_contract": "Contract Status",
      "end_date": "End: ",
      "bought_date": "Bought: ",
      "view_receipt": "Show receipt",
      "equipment_value": "equipment value",
      "warranty_period": "Warranty Period",
      "protection_until": "Protection until: ",
      "issued_date": "Issued: ",
      "view_attachment": "View attachment",
      "validity_status": "Validity Status",
      "valid_until": "Valid until: ",
      "modal_title_contract": "New Contract",
      "modal_title_warranty": "New Equipment",
      "modal_title_certificate": "New Document / Certificate",
      "name_label_contract": "Name (e.g. UPC Internet)",
      "name_label_warranty": "Name (e.g. Bosch Washing Machine)",
      "name_label_certificate": "Name (e.g. Driver's License, Work Contract, SEP)",
      "attachment_label": "Attachment (Scan, PDF, Photo)",
      "click_to_upload": "Click to upload file",
      "date_start_cert": "Date of achievement / issue",
      "date_start_contract": "Date of conclusion",
      "date_start_warranty": "Date of purchase",
      "date_end_cert": "Valid until (Optional)",
      "date_end_contract": "End of contract",
      "date_end_warranty": "End of warranty",
      "cost_label": "Amount / Cost",
      "cost_desc_contract": "Subscription cost (PLN)",
      "cost_desc_warranty": "Purchase amount (PLN)",
      "recurring_billing": "Cyclic billing (Subscription)",
      "one_time_billing": "One-time payment",
      "create_expense": "Automatically add expense to calendar at start date",
      "notes_label": "Notes / Additional information",
      "cancel_btn": "Cancel",
      "save_btn": "Save Document",
      "saving": "Saving..."
    }
  },
  pl: {
    drawer_page: {
      "title": "Cyfrowa Szuflada",
      "subtitle": "Zarządzaj swoimi umowami, sprzętem i ważnymi dokumentami",
      "tab_contracts": "Umowy i Abonamenty",
      "tab_warranties": "Sprzęt i Gwarancje",
      "tab_certificates": "Certyfikaty i Inne",
      "add_contract": "Dodaj nową umowę",
      "add_warranty": "Dodaj nowy sprzęt",
      "add_certificate": "Dodaj nowy dokument",
      "delete_confirm": "Czy na pewno chcesz usunąć ten dokument ze schowka?",
      "progress_no_limit": "Bezterminowo",
      "progress_expired": "Wygasło",
      "progress_left": "Pozostało {days} dni",
      "empty_contracts": "Nie masz jeszcze dodanych umów. Kliknij przycisk wyżej, aby dodać pierwszą.",
      "empty_warranties": "Brak zapisanych sprzętów i gwarancji.",
      "empty_certificates": "Brak zapisanych certyfikatów i dokumentów.",
      "from_date": "Od: ",
      "view_document": "Zobacz dokument",
      "cost_recurring": "/ cykl",
      "cost_one_time": "jednorazowo",
      "status_contract": "Status umowy",
      "end_date": "Koniec: ",
      "bought_date": "Kupiono: ",
      "view_receipt": "Pokaż paragon",
      "equipment_value": "wartość sprzętu",
      "warranty_period": "Okres Gwarancji",
      "protection_until": "Ochrona do: ",
      "issued_date": "Wydano: ",
      "view_attachment": "Zobacz załącznik",
      "validity_status": "Status Ważności",
      "valid_until": "Ważne do: ",
      "modal_title_contract": "Nowa Umowa",
      "modal_title_warranty": "Nowy Sprzęt",
      "modal_title_certificate": "Nowy Dokument / Certyfikat",
      "name_label_contract": "Nazwa (np. Internet UPC)",
      "name_label_warranty": "Nazwa (np. Pralka Bosch)",
      "name_label_certificate": "Nazwa (np. Prawo Jazdy, Umowa o Pracę, SEP)",
      "attachment_label": "Załącznik (Skan, PDF, Zdjęcie)",
      "click_to_upload": "Kliknij, aby wgrać plik",
      "date_start_cert": "Data uzyskania / wydania",
      "date_start_contract": "Data zawarcia",
      "date_start_warranty": "Data zakupu",
      "date_end_cert": "Ważne do (Opcjonalnie)",
      "date_end_contract": "Zakończenie umowy",
      "date_end_warranty": "Koniec gwarancji",
      "cost_label": "Kwota / Koszt",
      "cost_desc_contract": "Koszt abonamentu (PLN)",
      "cost_desc_warranty": "Kwota zakupu (PLN)",
      "recurring_billing": "Rozliczanie cykliczne (Abonament)",
      "one_time_billing": "Jednorazowa opłata",
      "create_expense": "Dodaj automatycznie wydatek w kalendarzu w dniu startu",
      "notes_label": "Notatki / Dodatkowe informacje",
      "cancel_btn": "Anuluj",
      "save_btn": "Zapisz Dokument",
      "saving": "Zapisywanie..."
    }
  }
};

for (const lang of languages) {
  const filePath = `d:/Code/PersonalData/local-finance-dashboard/src/lib/i18n/dictionaries/${lang}.json`;
  let fileData = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  fileData.drawer_page = translations[lang].drawer_page;
  fs.writeFileSync(filePath, JSON.stringify(fileData, null, 2), 'utf8');
}
console.log("Dictionaries updated");
